# Generated by Django 4.2.5 on 2023-09-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(default="", upload_to="produtos/"),
            preserve_default=False,
        ),
    ]
