# Generated by Django 4.2.5 on 2023-09-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0002_produto_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
